services:
  estaciona-postgres:
    image: docker.io/library/postgres:14.19
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-estacionaadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teste123}
      POSTGRES_DB: ${POSTGRES_DB:-estacionarapido}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-estacionaadmin} -d ${POSTGRES_DB:-estacionarapido}"]
      interval: 10s
      timeout: 5s
      retries: 5

  estaciona-quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      estaciona-postgres:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER:-estacionaadmin}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-teste123}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://estaciona-postgres:5432/${POSTGRES_DB:-estacionarapido}
